Repository Last-Survivors-3-8/Watcher-Habit-Server, pull requests merged in 2023-09, with the labels that each got.

#2 Set GitHub Actions CI 및 코드 스타일 수정
  .github/workflows/codeStyle.yml
  .github/workflows/nodejs.yml
  README.md
  package.json
  src/bin/www
  src/utils/ERRORS.js
Labels: duplicate

#3 Feature 유저 관련 api
  .eslintrc.json
  package-lock.json
  package.json
  src/loaders/errorHandlers.js
  src/loaders/routes.js
  src/middlewares/middlewares
  src/middlewares/validateUser.js
  src/models/Habit.js
  src/models/User.js
  src/routes/user.js
  src/utils/ERRORS.js
Labels: enhancement

#4 Feature 습관 관련 api
  .eslintrc.json
  src/controllers/controllers
  src/controllers/habitController.js
  src/loaders/routes.js
  src/middlewares/commonErrorHandler.js
  src/middlewares/validateHabit.js
  src/middlewares/validateMiddleware.js
  src/models/Habit.js
  src/routes/habit.js
  src/routes/user.js
  src/services/habitService.js
  src/utils/ERRORS.js
  src/utils/handleError.js
Labels: enhancement

#6 Feature 유저별/그룹별 일간 습관 목록 조회 api
  src/controllers/groupController.js
  src/controllers/habitController.js
  src/controllers/userController.js
  src/lib/getLoginUserId.js
  src/loaders/routes.js
  src/middlewares/validateGroup.js
  src/middlewares/validateUser.js
  src/middlewares/verifyGroupMember.js
  src/routes/group.js
  src/routes/user.js
  src/services/groupService.js
  src/services/habitService.js
  src/services/userService.js
  src/utils/dateToDay.js
Labels: enhancement

#8 Feature 알림 관련 api
  src/controllers/notificationController.js
  src/lib/ERRORS.js
  src/loaders/routes.js
  src/middlewares/validateNotification.js
  src/models/Habit.js
  src/routes/notification.js
  src/services/habitService.js
  src/services/notificationService.js
  src/utils/getDateDiffFromToday.js
Labels: enhancement

#10 Feature 습관 지켜보기 등록, 해제 api
  src/controllers/habitController.js
  src/lib/ERRORS.js
  src/middlewares/validateHabit.js
  src/routes/habit.js
  src/services/habitService.js
Labels: enhancement

#11 그룹 관련 api
  src/controllers/groupController.js
  src/controllers/habitController.js
  src/lib/ERRORS.js
  src/middlewares/validateGroup.js
  src/models/Group.js
  src/models/Habit.js
  src/routes/group.js
Labels: enhancement

#13 Feature 인증 상태 수정 관련 api 작업
  src/services/habitService.js
Labels: enhancement

#12 Feature 초대 관련 api
  src/controllers/groupController.js
  src/controllers/userController.js
  src/lib/ERRORS.js
  src/middlewares/validateGroup.js
  src/routes/group.js
  src/routes/user.js
  src/utils/sseConnections.js
Labels: enhancement

#14 Feature 기한별 습관 목록 조회 api
  src/controllers/habitController.js
  src/middlewares/validateHabit.js
  src/routes/habit.js
  src/services/habitService.js
Labels: enhancement

#15 Fix 알림 연동 api 수정
  src/controllers/habitController.js
  src/models/Notification.js
  src/routes/notification.js
  src/services/habitService.js
  src/services/notificationService.js
Labels: bug, enhancement

#17 Fix 기한별 습관 목록 조회 및 초대 알림 컨트롤러 수정
  src/controllers/groupController.js
  src/controllers/habitController.js
  src/services/habitService.js
Labels: bug, enhancement

#16 Feature 습관 상태 관리 배치
  src/bin/www
  src/controllers/eventsController.js
  src/lib/ERRORS.js
  src/lib/updateHabitStatus/createAndSendNotification.js
  src/lib/updateHabitStatus/getIncrementedTime.js
  src/lib/updateHabitStatus/getKSTDateAndTime.js
  src/lib/updateHabitStatus/handleExpiredFailureStatus.js
  src/lib/updateHabitStatus/sendNotificationsForStatus.js
  src/lib/updateHabitStatus/updateAllHabits.js
  src/lib/updateHabitStatus/updateApprovalStatus.js
  src/lib/updateHabitStatus/updateHabitStatus.js
  src/loaders/routes.js
  src/middlewares/validateUser.js
  src/routes/events.js
  src/services/habitService.js
  src/utils/cronJob.js
  src/utils/sendNotification.js
Labels: enhancement

#18 Feature 이전 습관 기록 저장
  src/lib/dailyHabitsBackup/dailyHabitsBackup.js
  src/lib/initializeHabit.js
  src/lib/updateHabitStatus/getIncrementedTime.js
  src/lib/updateHabitStatus/updateAllHabits.js
  src/lib/updateHabitStatus/updateHabitStatus.js
  src/models/HabitHistory.js
  src/utils/cronJob.js
Labels: enhancement

#19 Feature 알림 상태 업데이트 배치 및 추가 작업
  src/controllers/groupController.js
  src/controllers/habitController.js
  src/lib/dailyHabitsBackup/dailyHabitsBackup.js
  src/lib/realTimeNotifications/createAndSendNotification.js
  src/lib/realTimeNotifications/sendNotificationsForStatus.js
  src/lib/realTimeNotifications/sendSseNotification.js
  src/lib/updateHabitStatus/updateAllHabits.js
  src/lib/updateHabitStatus/updateApprovalStatus.js
  src/lib/updateHabitStatus/updateHabitStatus.js
  src/lib/updateIsNeedToSend/updateIsNeedToSend.js
  src/routes/auth.js
  src/services/habitService.js
  src/utils/cronJob.js
  src/utils/sendNotification.js
Labels: enhancement
